fetch_history:
  name: Fetch history
  description: Fetches historical hourly data from the Energa API.
  fields:
    start_date:
      name: Start date
      description: Date to start fetching from (format YYYY-MM-DD).
      required: true
      selector:
        text:
    days:
      name: Number of days
      description: How many days to fetch (default 30).
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 365
